### ISSUE TITLE
Broken `--resolve-symlinks` option

### ISSUE THREAD

**Issue by alou-S** [agnostic-apollo/bindfs#1]
If a folder is mounted using the `bindfs --resolve-symlinks` option this breaks the permissions of the mounted directory completely. Thus you cannot use the directory in any way even as root.

Using the arm7 version on Android 11.

**Comment by alou-S** [comment]
The issue is more related to SELinux than bindfs itself.

**Comment by agnostic-apollo** [comment]
Thanks. Sorry, didn't get time myself to look into it.

**Comment by alou-S** [comment]
Can you update and release the latest release of bindfs binaries?
Also is it possible to add it to the Termux Repository since it has various uses on Android (Alot more when SE Linux is disabled)
